spring:
  profiles:
    active: "docker_windows"
  datasource:
    username: "root"
    password: "admin2193"
    driver-class-name: "com.mysql.jdbc.Driver"
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"

---
spring:
  profiles: "local"
  datasource:
    url: "jdbc:mysql://localhost:3306/shopping-cart?useSSL=false"

---

spring:
  profiles:
    active: "unit-test"
  datasource:
    username: sa
    password: sa
    url: "jdbc:h2:mem:shopping-cart-db;DB_CLOSE_DELAY=-1"
    driver-class-name: "org.h2.Driver"

---
spring:
  profiles: "docker_windows"
  datasource:
    url: "jdbc:mysql://192.168.99.100:3306/shopping-cart?useSSL=false"

